# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    default.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hshimizu <hshimizu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/08 13:47:37 by hshimizu          #+#    #+#              #
#    Updated: 2025/04/30 14:35:14 by hshimizu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

servers:
  # Server to serve static files
  - server_names: [localhost]
    listen:
      - { port: 8080 }
      - { host: "::", port: 8081 }
    client_max_body_size: 10M
    error_pages:
      - { code: 404, path: /home/hshimizu/webserv/html/404.html }
      - { code: 500, path: /home/hshimizu/webserv/html/500.html }
    locations:
      - path: /
        type: default
        root: /
        index: [index.html, index.htm]
        autoindex: true
        cgi:
          - { ext: .py, bin: /usr/bin/python3 }
          - { ext: .php, bin: /usr/bin/php-cgi }
      - path: /upload
        type: upload
        store: ~/uploads
  # Server to redirect to profile
  - server_names: [hshimizu.42.fr, hshimizu.42tokyo.jp]
    listen:
      - { port: 8080 }
      - { port: 8082 }
    locations:
      - path: /
        allow_methods: [GET, HEAD]
        type: redirect
        code: 301
        redirect: https://profile.intra.42.fr/users/hshimizu
