servers:
  - server_names: [hshimizu.42.fr, hshimizu.42tokyo.jp]
    listen:
      - { port: 8080 }
    locations:
      - path: /
        type: redirect
        code: 301
        redirect: https://profile.intra.42.fr/users/hshimizu
  - server_names: [localhost]
    listen:
      - { port: 8080 }
      - { host: "::", port: 8081 }
    client_max_body_size: 10M
    error_pages:
      - { code: 404, path: /404.html }
      - { code: 500, path: /500.html }
    locations:
      - path: /
        type: default
        root: ~/html
        index: [index.html, index.htm]
        autoindex: true
        cgi:
          .py: { bin: /usr/bin/python3 }
          .php: { bin: /usr/bin/php-cgi }
      - path: /upload
        type: upload
        store: ~/uploads
